import { GoogleGenerativeAI } from '@google/generative-ai';
import { ProjectContext } from '../analyzer';

/**
 * Generates a concise project description using the Google Gemini AI.
 * 
 * @param ctx - The project context containing metadata like name, framework, and dependencies.
 * @returns A 2-3 sentence compelling project description generated by AI.
 * @throws Error if GEMINI_API_KEY is not set in environment variables.
 */
export async function generateAiDescription(ctx: ProjectContext): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is not set');
  }

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

  const prompt = `Given this project context, write a concise, compelling README description (2-3 sentences):
  Name: ${ctx.name}
  Language: ${ctx.language}
  Framework: ${ctx.framework}
  Dependencies: ${Object.keys(ctx.scripts).join(', ')}`;

  const result = await model.generateContent(prompt);
  const response = await result.response;
  return response.text();
}
